世界保护列表:
- zc
- jm
世界保护白名单:
PVP世界保护列表:
- zc
- jm
#######################################
传送世界提示信息: '传送完毕，你现在在[{world}]世界里'
世界保护提示信息: '该世界已被保护!'
世界列表提示信息: '世界列表:{list}'
PVP世界保护提示信息: '该世界不允许PVP'
世界不存在提示信息: '世界{world}不存在'
不是OP提示信息: '不是OP请一边凉快去'
#######################################